### ISSUE TITLE
Genshin 3.8 update status

### ISSUE THREAD

**Issue by Ash3781** [zeroday0619/MyLittleLutrisScripts#18]
Hey, since the 3.8 update basically just dropped, I would like to create a little patch tracker for that update with this issue

**Comment by scorninpc** [comment]
I think it's useless. Just add more pages to google crawle

i'll commit in 1 hour

**Comment by scorninpc** [comment]
The game is currently playable without patches

Anyway, test version commited. As usual, dont use main account since tested. unlock on 08/07 

https://github.com/zeroday0619/MyLittleLutrisScripts/commit/73b119e49dc17138a2155ccf20761e951c44132b

without patch, just run GenshinImpact.exe

Without path, if cannot login or open: rename `mhypbase.dll` to `mhypbase_.dll`

Some people report that game crash nor show error on screen/after-screen login. Try to go to the folder Genshin Impact/GenshinImpact_Data/Plugins/ and look for file `Telemetry.dll` and `telemetry.dll`. You need have only `telemetry.dll`, so if this file doesn't exist, rename `Telemetry.dll` to `telemetry.dll`. If exists, just delete `Telemetry.dll`

**Comment by scorninpc** [comment]
No changes!

- Just unpatch previous patch
- Start launcher
- Update
- Start game from oficial launcher

![image](https://github.com/zeroday0619/MyLittleLutrisScripts/assets/2607849/2c9c9dbe-5020-4334-946b-3da478419e20)
